package com.example.jaroslavistok.personalmobileassistantformanagingdiabetes.utils;


import android.content.DialogInterface;
import android.database.ContentObserver;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.net.Uri;

public interface DefaultsConstantsValues {
    String[] NO_PROJECTION = null;

    String[] ALL_COLUMNS = null;

    String NO_SELECTION = null;

    String[] NO_SELECTION_ARGS = null;

    String NO_SORT_ORDER = null;

    String NO_GROUP_BY = null;

    String NO_HAVING = null;

    String AUTOGENERATED_ID = null;

    SQLiteDatabase.CursorFactory DEFAULT_CURSOR_FACTORY = null;

    String NO_NULL_COLUMN_HACK = null;

    Cursor NO_CURSOR = null;

    ContentObserver NO_CONTENT_OBSERVER = null;

    int BEFORE_FIRST = -1;

    int NO_FLAGS = 0;

    Object NO_COOKIE = null;

    String NO_TYPE = null;

    Uri NO_URI = Uri.EMPTY;

    DialogInterface.OnClickListener DISMISS_ACTION = null;
}

